title: Jus de veau
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
favicon: images/favicon.png
logo_dark: images/logo.svg
logo_light: images/logo-white.svg
hamburger_background_image: /images/leaf-light-grey.svg
bg_image_primary: images/landscape-4350845_1920.jpg
bg_image_secondary: /images/leaf-light-grey.svg
bg_image_product: /images/leaf.svg
snipcart_api_key: MjQwYjY4YmMtMzc5MC00MTc4LThhZDMtNjJlM2ZjMmZjMjE2NjM3NDU5Njg3NTg1MDAxMDc4
footer_text: Copyright 2020 Planty Inc. All rights reserved.
palette: default
palettes:
  default:
    sass:
      default: '#FFFFFF'
      light: '#F0F0F0'
      medium: '#6B797A'
      dark: '#384647'
      active: '#88DD9B'
      active_light: '#C0FDB6'
      active_medium: '#5C9174'
      active_dark: '#547567'
      dark_grey: '#273132'
      light_grey: '#6B797A'
      bg_image_cart: /images/leaf-light-grey.svg
main_menu:
  - title: Store
    url: /store
  - title: About
    url: /about
  - title: FAQ
    url: /faq
sass:
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
